# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    labels:
      - "dependencies"
      - "patch"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "patch"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
