name-template: 'Schema.NET $RESOLVED_VERSION'
tag-template: 'Schema.NET.$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
categories:
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🚀 New Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES

  ## 👨🏼‍💻 Contributors

  $CONTRIBUTORS
autolabeler:
  - label: 'documentation'
    files:
      - '**/*.md'
  - label: 'enhancement'
    files:
      - 'Source/**/*'
      - 'Tools/**/*'
  - label: 'maintenance'
    files:
      - '.github/**/*'
      - 'Benchmarks/**/*'
      - 'Images/**/*'
      - 'Tests/**/*'
