//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema.NET.Tool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schema.NET.Tool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that a new primitive type has not been added..
        /// </summary>
        internal static string CheckThatNewPrimitiveTypeNotAdded {
            get {
                return ResourceManager.GetString("CheckThatNewPrimitiveTypeNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A class should only have one parent at this stage..
        /// </summary>
        internal static string ClassShouldOnlyHaveOneParent {
            get {
                return ResourceManager.GetString("ClassShouldOnlyHaveOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Class and Property Download.
        /// </summary>
        internal static string FinishedClassAndPropertyDownload {
            get {
                return ResourceManager.GetString("FinishedClassAndPropertyDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Clean Project Folder.
        /// </summary>
        internal static string FinishedCleanProjectFolder {
            get {
                return ResourceManager.GetString("FinishedCleanProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Write Classes.
        /// </summary>
        internal static string FinishedWriteClasses {
            get {
                return ResourceManager.GetString("FinishedWriteClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interface should only have one parent at this stage..
        /// </summary>
        internal static string InterfaceShouldOnlyHaveOneParent {
            get {
                return ResourceManager.GetString("InterfaceShouldOnlyHaveOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Class and Property Download.
        /// </summary>
        internal static string StartedClassAndPropertyDownload {
            get {
                return ResourceManager.GetString("StartedClassAndPropertyDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Clean Project Folder.
        /// </summary>
        internal static string StartedCleanProjectFolder {
            get {
                return ResourceManager.GetString("StartedCleanProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Write Classes.
        /// </summary>
        internal static string StartedWriteClasses {
            get {
                return ResourceManager.GetString("StartedWriteClasses", resourceCulture);
            }
        }
    }
}
