namespace Schema.NET
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;

    /// <summary>
    /// A Report generated by governmental or non-governmental organization.
    /// </summary>
    [DataContract]
    public partial class Report : Article
    {
        public interface IReportNumber : IValue {}
        public interface IReportNumber<T> : IReportNumber { new T Value { get; } }
        public class OneOrManyReportNumber : OneOrMany<IReportNumber>
        {
            public OneOrManyReportNumber(IReportNumber item) : base(item) { }
            public OneOrManyReportNumber(IEnumerable<IReportNumber> items) : base(items) { }
            public static implicit operator OneOrManyReportNumber (string value) { return new OneOrManyReportNumber (new ReportNumberstring (value)); }
            public static implicit operator OneOrManyReportNumber (string[] values) { return new OneOrManyReportNumber (values.Select(v => (IReportNumber) new ReportNumberstring (v))); }
            public static implicit operator OneOrManyReportNumber (List<string> values) { return new OneOrManyReportNumber (values.Select(v => (IReportNumber) new ReportNumberstring (v))); }
        }
        public struct ReportNumberstring : IReportNumber<string>
        {
            object IValue.Value => this.Value;
            public string Value { get; }
            public ReportNumberstring (string value) { Value = value; }
            public static implicit operator ReportNumberstring (string value) { return new ReportNumberstring (value); }
        }

        /// <summary>
        /// Gets the name of the type as specified by schema.org.
        /// </summary>
        [DataMember(Name = "@type", Order = 1)]
        public override string Type => "Report";

        /// <summary>
        /// The number or other unique designator assigned to a Report by the publishing organization.
        /// </summary>
        [DataMember(Name = "reportNumber", Order = 306)]
        public OneOrManyReportNumber ReportNumber { get; set; }
    }
}
