namespace Schema.NET
{
    using System;
    using System.Runtime.Serialization;

    /// <summary>
    /// A Report generated by governmental or non-governmental organization.
    /// </summary>
    [DataContract]
    public class Report : Article
    {
        /// <summary>
        /// Gets the name of the type as specified by schema.org.
        /// </summary>
        [DataMember(Name = "@type", Order = 1)]
        public override string Type => "Report";

        /// <summary>
        /// The number or other unique designator assigned to a Report by the publishing organization.
        /// </summary>
        [DataMember(Name = "reportNumber", Order = 2)]
        public string ReportNumber { get; set; }
    }
}
